### PR TITLE
Test on Elixir v1.9

### PR DESCRIPTION
**Pull request by evnu**
This adds a CircleCI build for Elixir v1.9.

### CODE REVIEW

**Comment by evnu** [comment]
I wonder if CircleCI will build this pull request..

**Comment by evnu** [comment]
@alfert You might need to check if CircleCI is run on pull requests.

**Comment by alfert** [comment]
@evnu Any clue why CircleCi is not running on this PR? The PR #114 is running.

**Comment by alfert** [comment]
💟 Thanks for this PR

**Comment by evnu** [comment]
> Any clue why CircleCi is not running on this PR? The PR #114 is running.

Either something broke since 19 days ago, or it is related to me also being using circleci. The branch itself ran on "my" circleci, maybe that is the cause.

**Pull request merged**
