### PR TITLE
Allow configuring counter examples path in config/

### LINKED ISSUE #115: Move counter-examples file to be configured via application configuration (config.exs)
Hello Alfert, do you have plans or would it be possible to change `prop check` to have the counter-examples files be configure via the standard application configuration (`config.exs` files) instead of via the `Mixfile`?

To us this would be useful to allow running applications depending on `propcheck` on slave nodes via Erlang's `slave` APIs. The problem resides in the slaves receiving the code paths from the code server (Erlang's `code` module), but ignoring the counter-examples file inside the `_build` dir. By having the counter-examples file configured via the application configuration we believe the slave nodes would be able to access the file. We do this with other dependencies who needs files and allow these to be configured via `config.exs`.

Right now, our workaround is to set the `app: false` flag on `mix.exs` dependency declaration for `propcheck`, and manually start `propcheck` in the ExUnit helper file. This allows our property tests to run in the master node, and allows the slave nodes to start up and execute because `prop check` won't look for the counter-examples file.

Thank you for your time and consideration 🙏

### PR DESCRIPTION
**Pull request by evnu**
This pull request extends configuration to store counter examples to the application environment. Now, the following is possible:

```elixir
config :propcheck, counter_examples: "location"
```

If the path is configured both in the project definition as well as in the application environment, the application environment takes precedence. As before, it is configured in neither location, it takes a default value.

Fix #115

### CODE REVIEW

**Comment by evnu** [comment]
@sashaafm Can you test if this works for you?

**Comment by evnu** [comment]
@alfert `property Default PBT Level 0` [failed again](https://travis-ci.org/alfert/propcheck/jobs/600960159), maybe we should mark it as often failing.. Interestingly, the last times I saw this it happened on Elixir v1.5, but not on the other versions. But this could very well be coincidence.

**Comment by sashaafm** [comment]
@evnu I’m no longer working on the particular project which needed this. I’ll try to find some time to experiment your changes

**Comment by evnu** [comment]
Rebased on current master.

**Comment by evnu** [comment]
Rebased on current master (cleaner history and let travis run again).

**Comment by evnu** [comment]
This has been open for quite some time. I guess we don't actually need this. Closing.

**Comment by sashaafm** [comment]
As indicated in the other issue https://github.com/alfert/propcheck/issues/190, could we get around to merging this?

**Comment by evnu** [comment]
Rebased on master. @sashaafm can you check if this works for you? If so, @alfert would you consider merging this, or should this be handled differently?

**Comment by alfert** [comment]
I restart now the build jobs after merging #191

**Comment by alfert** [comment]
Ah, this cannot work in this way. @evnu, I simply merged via the WebUI the master into this branch. Should only be the github actions.

**Pull request merged**
