### PR TITLE
Bump ex_doc

### LINKED ISSUE #194: Mix.Local.path_for/1 is deprecated
With Elixir v1.11:

```
warning: Mix.Local.path_for/1 is deprecated. Use Mix.path_for/1 instead
  mix.exs:77: Makeup.Mixfile.build_docs/1
```

### PR DESCRIPTION
**Pull request by evnu**
Fix #194

### CODE REVIEW

**Comment by alfert** [comment]
This is really strange. It seems to be spurious but a re-run of tests shows that the dialyzer bug is persistent.

**Comment by evnu** [comment]
The dialyzer error message:

```
1> [78, 111, 116, 32, 97, 32, 114, 101, 103, 117, 108, 97, 114, 32, 102, 105, 108, 101, 58, 32].
"Not a regular file: "
```

This looks related: https://github.com/jeremyjh/dialyxir/issues/301

**Comment by evnu** [comment]
@alfert I suspect that the dialyzer problem is related to caching of PLTs.

**Comment by alfert** [comment]
Somewhat late, but I had similar problems with caching when using BitBucket's internal CI for another project. Seems not to be the best option.

**Pull request merged**
