### PR TITLE
Replace travis with CircleCI

### LINKED ISSUE #96: Fix CI
It seems that travis is no longer called when pull requests are submitted. Can this be fixed?

### PR DESCRIPTION
**Pull request by evnu**
This pull request replaces travis with circleci in an attempt to Fix #96.

@alfert Feel free to close this PR if you prefer to stay with travis or another CI platform. Note that you probably have to register with CircleCI and follow `propcheck` to make this PR work.

### CODE REVIEW

**Comment by evnu** [comment]
[This](https://circleci.com/gh/evnu/propcheck) is what the UI of CircleCI looks like.

**Comment by evnu** [comment]
For a single test run over multiple elixir versions, the UI looks [like this](https://circleci.com/workflow-run/f65c8c7b-0c12-4d98-a305-012f0f542a47).

**Comment by alfert** [comment]
Let's give it a try!

**Comment by evnu** [comment]
Integration seems to work, see https://github.com/alfert/propcheck/pull/95. CircleCI is running its tests after I force-pushed a rebase.

**Pull request merged**
