### PR TITLE
Convert whitespace in test files with mixed tabs and spaces

### PR DESCRIPTION
**Pull request by ryanwinchester**
It is really hard to read some of the test files in github since there is mixing of tabs and spaces (and github renders tabs as 8 spaces)

I tried to limit formatting changes to just the whitespace although it was very tempting to change a lot of other stuff 😅

### CODE REVIEW

**Comment by alfert** [comment]
Indeed, the diffs are looking way more consistent. Thank you! Could you please do a rebase to reflect the other PR? After that I will merge. 

What is the other stuff you would like to change? Running the Elixir formatter on the sources?

**Comment by ryanwinchester** [comment]
> Indeed, the diffs are looking way more consistent. Thank you! Could you please do a rebase to reflect the other PR? After that I will merge.

Done.

> What is the other stuff you would like to change? Running the Elixir formatter on the sources?

Not necessarily, but that would definitely help with readability.

**Comment by ryanwinchester** [comment]
@alfert just for fun I ran the formatter on the `test` dir in this branch https://github.com/ryanwinchester/propcheck/blob/feature/formatter/test/movie_test.exs

**Comment by ryanwinchester** [comment]
Example:

### Original:

```elixir
  def command(state = %__MODULE__{rented: rented}) do
		movies_rented = 0 < (rented |> Map.values() |> List.flatten() |> Enum.count())
		std_calls = [{1, {:call, MovieServer, :create_account, [name()]}},
           {1, {:call, MovieServer, :ask_for_popcorn, []}},
           {1, {:call, MovieServer, :delete_account, [password(state)]}},
           {1, {:call, MovieServer, :rent_dvd, [password(state), movie()]}}]
		calls = if (movies_rented) do
				pms = user_movie_pairs(rented)
				#IO.puts "User/movie pairs: #{inspect pms}"
     		[{5,	let {p, m} <- elements(pms) do
						{:call, MovieServer, :return_dvd, [p, m]}
				 end} | std_calls]
			else
				#IO.puts "Nothing rented, no returns generated"
				std_calls
			end

    frequency(calls)
end
```

### This PR:

```elixir
  def command(state = %__MODULE__{rented: rented}) do
    movies_rented = 0 < (rented |> Map.values() |> List.flatten() |> Enum.count())

    std_calls = [{1, {:call, MovieServer, :create_account, [name()]}},
      {1, {:call, MovieServer, :ask_for_popcorn, []}},
      {1, {:call, MovieServer, :delete_account, [password(state)]}},
      {1, {:call, MovieServer, :rent_dvd, [password(state), movie()]}}]

    calls =
      if (movies_rented) do
        pms = user_movie_pairs(rented)
        #IO.puts "User/movie pairs: #{inspect pms}"
        [{5, let {p, m} <- elements(pms) do
          {:call, MovieServer, :return_dvd, [p, m]}
        end} | std_calls]
      else
        #IO.puts "Nothing rented, no returns generated"
        std_calls
      end

    frequency(calls)
  end
```

### Formatter:

```elixir
  def command(state = %__MODULE__{rented: rented}) do
    movies_rented = 0 < rented |> Map.values() |> List.flatten() |> Enum.count()

    std_calls = [
      {1, {:call, MovieServer, :create_account, [name()]}},
      {1, {:call, MovieServer, :ask_for_popcorn, []}},
      {1, {:call, MovieServer, :delete_account, [password(state)]}},
      {1, {:call, MovieServer, :rent_dvd, [password(state), movie()]}}
    ]

    calls =
      if movies_rented do
        pms = user_movie_pairs(rented)
        # IO.puts "User/movie pairs: #{inspect pms}"
        [
          {5,
           let {p, m} <- elements(pms) do
             {:call, MovieServer, :return_dvd, [p, m]}
           end}
          | std_calls
        ]
      else
        # IO.puts "Nothing rented, no returns generated"
        std_calls
      end

    frequency(calls)
  end
```
### Additional tweaks:

```elixir
  def command(state = %__MODULE__{rented: rented}) do
    movies_rented =
      rented
      |> Map.values()
      |> List.flatten()
      |> Enum.count()

    std_calls = [
      {1, {:call, MovieServer, :create_account, [name()]}},
      {1, {:call, MovieServer, :ask_for_popcorn, []}},
      {1, {:call, MovieServer, :delete_account, [password(state)]}},
      {1, {:call, MovieServer, :rent_dvd, [password(state), movie()]}}
    ]

    calls =
      if movies_rented > 0 do
        pms = user_movie_pairs(rented)
        # IO.puts "User/movie pairs: #{inspect pms}"

        add_calls =
          let {p, m} <- elements(pms) do
            {:call, MovieServer, :return_dvd, [p, m]}
          end

        [{5, add_calls} | std_calls]
      else
        # IO.puts "Nothing rented, no returns generated"
        std_calls
      end

    frequency(calls)
  end
```

**Comment by alfert** [comment]
I like your additional tweaks, that is something what a formatter cannot do. Since the test cases - in particular for the stateful tests - are effectively part of the documentation, a nicely formatted version is an important asset, which I ignored a long time. So, if you like to provide a PR in the style above, I am glad to merge it.

**Pull request merged**
