### PR TITLE
ci: Store core and crash dumps

### PR DESCRIPTION
**Pull request by evnu**
Part of #101. Enable storing crash and core dumps in CircleCI. See [the documentation](https://circleci.com/docs/2.0/artifacts/#uploading-core-files) on how to retrieve such artifacts, if any core or crash dumps were written.

### CODE REVIEW

**Comment by evnu** [comment]
@alfert Configuring CircleCI is a bit cumbersome, as the YAML configuration is easy to get wrong. I found [validating the config locally](https://circleci.com/blog/circleci-hacks-validate-circleci-config-on-every-commit-with-a-git-hook/) to be useful.

**Comment by alfert** [comment]
This is a sweet bug 🤕  : The build fails if no erlang crash occurs. Build automation can be complicated ...
And yes: The idea of locally checking is great except that you also need to have a tool from CircleCI locally installed, if I understand it correctly.

**Comment by evnu** [comment]
> The idea of locally checking is great except that you also need to have a tool from CircleCI locally installed, if I understand it correctly.

I downloaded the release directly from [github](https://github.com/CircleCI-Public/circleci-cli/releases), unpacked it and ran the tool directly from that directory. The `wget | sh` command is not needed.

**Comment by evnu** [comment]
I also tried to inject a failure to check if CircleCI will try to attempt to copy the crash dumps. See [here](https://circleci.com/gh/evnu/propcheck/109) for such an experiment. That run has an additional step (`mkdir`,..), where CircleCI attempts to copy `erl_crash.dump` and `core.*`. So hopefully this will store dumps on CI the next time it happens.

**Comment by evnu** [comment]
@alfert Anything more to do here?

**Comment by alfert** [comment]
No, sorry, just too much other things. Thanks for this improvement!

**Pull request merged**
