### PR TITLE
Clarify `such_that` docs

### PR DESCRIPTION
**Pull request by x4lldux**
Improved docs for situation mentioned in #139

### CODE REVIEW

**Comment by alfert** [comment]
Thanks for the new test, that makes it more prominent. 

But, to be honest, I do not really understand what the problem is. Is the approach of Proper that it tries to generate valid data for the small size values (which would not succeed here) and then give up before trying larger size values?

**Comment by x4lldux** [comment]
PropEr generates an instance for the current size. If all constrains pass, *only* then it grows the size and tries the same with a "bigger" instance. In case of #139 it gives up before trying any larger size because it cannot create a valid instance that satisfies the list length constraint.

**Comment by alfert** [comment]
Thanx, now I got it. This means essentially that if the constraint is concerned with the size parameter of the outer generator (here length, which is the size of generator list), then `such_that` is not a good candidate or requires a smart setting of `start_size`.  I propose to add a remark of this kind to the docs and then we are done.

**Comment by x4lldux** [comment]
That doesn't apply just to outer generators nor only to generators that have an easy to grasp "size" property like a list or a binary. For an `integer()` generator small _size_ just means smaller integers being generated and `such_that(n <- int(), when: abs(n) > 100)` would also *"never"* work (if my math is correct there's like a _0.00001_<sup>_constraint_tries_</sup> chance of success for that example).
I'll try to create a better description for that for `such_that` macro.

**Comment by x4lldux** [comment]
@alfert I've pushed the updated docs.

**Comment by alfert** [comment]
💚 Thanks for that PR!

**Pull request merged**
